In [9]:
import pandas as pd

In [13]:
df = pd.read_csv('lecture01_bacterial_expression.csv')
df.head(2)

  sample_id species treatment  gene_a  gene_b  gene_c  growth_rate   response
0       S01  E_coli   control     5.1     2.0     7.2         0.91  sensitive
1       S02  E_coli      drug     8.2     3.8     6.1         0.42  resistant

In [15]:
df = pd.read_csv('lecture01_bacterial_expression.tsv',sep='\t')
df.head()

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
4,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive

In [17]:
df = pd.read_excel('lecture01_bacterial_expression.xlsx')
df.head()

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
4,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive

          gene_a     gene_b     gene_c  growth_rate
count  11.000000  12.000000  12.000000    12.000000
mean    6.418182   3.091667   6.983333     0.655000
std     1.672614   0.811797   0.818905     0.231222
min     4.700000   2.000000   5.800000     0.350000
25%     5.000000   2.425000   6.400000     0.457500
50%     5.500000   3.100000   6.950000     0.665000
75%     7.900000   3.825000   7.475000     0.872500
max     9.000000   4.100000   8.200000     0.910000